# Generated by Django 4.1.4 on 2023-07-24 13:48

import ModelApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminValue', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=ModelApp.models.User, to='ModelApp.user')),
            ],
        ),
    ]
