# Generated by Django 4.1.4 on 2023-07-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0002_alter_user_id_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profilePhoto',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='admin',
            name='adminValue',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelApp.user'),
        ),
    ]
