# Generated by Django 4.1.4 on 2023-07-24 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0003_admin_profilephoto_alter_admin_adminvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
