# Generated by Django 4.1.4 on 2023-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('pId', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
            ],
        ),
    ]
