# Generated by Django 4.1.4 on 2023-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_post_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title1',
            field=models.CharField(max_length=30),
        ),
    ]
