# Generated by Django 4.1.4 on 2023-07-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_comment1_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment1',
            new_name='Comment',
        ),
    ]
